# https://gitlab.com/RA-GAS-GmbH/rgms_konfig/-/ci/lint
variables:
    APT_CACHE_DIR: apt-cache

cache:
    key: "$CI_JOB_NAME"
    untracked: true
    paths:
    - apt-cache/
    - cargo/
    - target/

stages:
  - build
  - test
  - package

before_script:
    - mkdir -pv $APT_CACHE_DIR
    - apt-get -qq update
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" -qq -y install libudev-dev libgtk-3-dev clang
    - export PATH="/root/.cargo/bin:$PATH"

build:1.43:
    image: "rust:1.43"
    stage: build
    script:
    - cargo update
    - cargo build --verbose

build:stable:
    image: "rust:latest"
    stage: build
    script:
    - cargo update
    - cargo build --verbose

build:nightly:
    image: rustlang/rust:nightly
    stage: build
    allow_failure: true
    script:
    - cargo update
    - cargo build --verbose

test:rustfmt:
    image: "rust:latest"
    stage: test
    allow_failure: true
    script:
      - rustup component add rustfmt
      - cargo update
      - cargo build --verbose
      - cargo test
      - cargo fmt -- --check

# >>>>>>>>>>>>>> Kunden Version! <<<<<<<<<<<<<<<<<<
package:customer:
    image: "rust:latest"
    stage: package
    script:
    - cargo update
    - cargo build --release
    - cp target/release/rgms_konfig rgms_konfig
    artifacts:
      paths:
        - resources/about.png
        - resources/Hilfe.pdf
        - resources/rgms_konfig.ico
        - resources/Sensor-MB-*Rreg.csv
        - resources/style.css
        - CHANGELOG.md
        - LICENSE
        - README.md
        - rgms_konfig
      name: rgms_konfig-linux-x86_64

# >>>>>>>>>>>>>> RA-GAS Version! <<<<<<<<<<<<<<<<<<
package:ra-gas:
    image: "rust:latest"
    stage: package
    script:
    - cargo update
    - cargo build --release --features=ra-gas
    - cp target/release/rgms_konfig rgms_konfig
    artifacts:
      paths:
        # RA-GAS interne Version enthält die Software-Beschreibungen
        - resources/*"_Beschreibung_RA-GAS Sensor-MB.pdf"
        - resources/about.png
        - resources/Hilfe-ra-gas.pdf
        - resources/rgms_konfig-ra-gas.ico
        - resources/Sensor-MB-*.csv
        - resources/style*.css
        - CHANGELOG.md
        - LICENSE
        - README.md
        - rgms_konfig
      name: rgms_konfig-ra-gas-linux-x86_64
