# https://gitlab.com/RA-GAS-GmbH/rgms_konfig/-/ci/lint
variables:
    APT_CACHE_DIR: apt-cache

cache:
    key: "$CI_JOB_NAME"
    untracked: true
    paths:
    - apt-cache/
    - cargo/
    - target/

stages:
  - build
  - test
  - package

before_script:
    - mkdir -pv $APT_CACHE_DIR
    - apt-get -qq update
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" -qq -y install libudev-dev libgtk-3-dev clang
    - export PATH="/root/.cargo/bin:$PATH"

build:1.43:
    image: "rust:1.43"
    stage: build
    script:
    - cargo update
    - cargo build --verbose

build:stable:
    image: "rust:latest"
    stage: build
    script:
    - cargo update
    - cargo build --verbose

build:nightly:
    image: rustlang/rust:nightly
    stage: build
    allow_failure: true
    script:
    - cargo update
    - cargo build --verbose

test:rustfmt:
    image: "rust:latest"
    stage: test
    allow_failure: true
    script:
      - rustup component add rustfmt
      - cargo update
      - cargo build --verbose
      - cargo test
      - cargo fmt -- --check

package:customer:
    variables:
        NAME_SUFIX: ""
    image: "rust:latest"
    artifacts:
      paths:
        - resources/about.png
        - resources/Hilfe$NAME_SUFFIX.pdf
        - resources/style*.css
        - resources/*.ico
        - resources/*.csv
        - CHANGELOG.md
        - LICENSE
        - README.md
        - rgms_konfig$NAME_SUFFIX
      name: rgms_konfig$NAME_SUFFIX-"$CI_BUILD_REF_NAME"-linux-x86_64
    stage: package
    script:
    - cargo update
    - cargo build --release
    - cp target/release/rgms_konfig rgms_konfig$NAME_SUFFIX

package:ra-gas:
    variables:
        NAME_SUFIX: "-ra-gas"
    image: "rust:latest"
    artifacts:
      paths:
        # RA-GAS interne Version enthält die Beschreibungen
        - resources/*"_Beschreibung_RA-GAS Sensor-MB.pdf"
        - resources/about.png
        - resources/Hilfe$NAME_SUFFIX.pdf
        - resources/style*.css
        - resources/*.ico
        - resources/*.csv
        - CHANGELOG.md
        - LICENSE
        - README.md
        - rgms_konfig$NAME_SUFFIX
      name: rgms_konfig$NAME_SUFFIX-"$CI_BUILD_REF_NAME"-linux-x86_64
    stage: package
    script:
    - cargo update
    - cargo build --release --features=ra-gas
    - cp target/release/rgms_konfig rgms_konfig$NAME_SUFFIX
