language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - GTK=3.14 FEATURES=
  - GTK=3.24 FEATURES=v3_16
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libudev-dev libgtk-3-dev
script:
  - cargo build --verbose
  - cargo test --verbose
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
  ⋮ # rest of your existing "before_cache"
