[package]
name = "rgms_konfig"
version = "0.1.0"
authors = ["Stefan Müller <zzeroo> <co@zzeroo.com>"]
edition = "2018"

[dependencies]
csv = "1.1.3"
serde = { version = "1", features = ["derive"] }
tokio-serial = "4.3.3"
tokio-modbus = "0.4.0"
tokio = { version = "0.2.22", features = ["sync"] }
futures = "0.3.5"
